## Preprocesado del conjunto 1M


### Extraccion de los géneros de peliculas como vector One-Hot

In [24]:
import pandas as pd

PATH = '/Users/antonio/OneDrive - farmasturias.org/DOCTORADO/paper_generos_peliculas/XAI_movies/cjtos/ml-1m/'

#si COF esta ruta
PATH = 'c:\\Users\\antonio.cof\OneDrive - farmasturias.org\\DOCTORADO\\paper_generos_peliculas\\XAI_movies\\cjtos\\ml-1m\\'

In [25]:
pelis=pd.read_csv(PATH+"movies.dat",sep='::',engine='python')

In [26]:
pelis

,movieId,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

Los generos vienen en la columna genres separados por una barra.
genero primero un conjunto con las distintas variaciones

In [27]:
cto_generos=set()
generos=set()
cto_generos=set(pelis["genres"])

In [28]:
len(cto_generos)

301

recorremos todas las combinaciones y añadimos los valores a un conjunto (no admite duplicados)

In [29]:
for e in cto_generos:
    spl=e.split(sep='|')
    for g in spl:
        generos.add(str(g))

In [30]:
datageneros=pd.DataFrame(list(generos))

In [31]:
datageneros

              0
0        Action
1       Musical
2       Romance
3       Mystery
4         Crime
5        Horror
6       Fantasy
7   Documentary
8         Drama
9        Sci-Fi
10    Animation
11    Adventure
12     Thriller
13   Children's
14    Film-Noir
15       Comedy
16      Western
17          War

la funcion get_dummies nos genera la codificación one-hot

In [32]:
onehot=pd.get_dummies(datageneros)

In [33]:
onehot

,0_Action,0_Adventure,0_Animation,0_Children's,0_Comedy,0_Crime,0_Documentary,0_Drama,0_Fantasy,0_Film-Noir,0_Horror,0_Musical,0_Mystery,0_Romance,0_Sci-Fi,0_Thriller,0_War,0_Western
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
15,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [34]:
final=datageneros.merge(onehot,how='inner', left_index=True, right_index=True)

In [35]:
final=final.rename(columns={0:'literal'})
final

,literal,0_Action,0_Adventure,0_Animation,0_Children's,0_Comedy,0_Crime,0_Documentary,0_Drama,0_Fantasy,0_Film-Noir,0_Horror,0_Musical,0_Mystery,0_Romance,0_Sci-Fi,0_Thriller,0_War,0_Western
0,Action,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Musical,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,Romance,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,Mystery,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,Crime,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
5,Horror,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
6,Fantasy,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
7,Documentary,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
8,Drama,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,Sci-Fi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,Animation,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,Adventure,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,Thriller,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
13,Children's,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,Film-Noir,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
15,Comedy,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
16,Western,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
17,War,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

 puesto que cada pelicula puede tener mas un genero sumamos los vectores one-hot de cada genero de la misma
 para ello recorremos las 62,000 peliculas

#### Iteramos todas las peliculas

In [38]:
a=0
result=pd.DataFrame()
for index,row in pelis.iterrows():
    a+=1
    if a%100==0:
        print(a)
    dataframe=pd.DataFrame()
    genrer_peli=row["genres"]
    gen=genrer_peli.split(sep='|')
    for g in gen:
        match=final[final["literal"]==g]
        dataframe=dataframe.append(match)
    serie=dataframe[:][0:].sum()
    valoracion=pd.Series(row["title"]).append(serie) # ver si se puede eliminar todo esto del rename
    valoracion=valoracion.rename(index={0:'title'})
    valoracion=pd.Series(row["movieId"]).append(valoracion)
    result=result.append(valoracion,ignore_index=True)

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800

In [39]:
result=result.rename(columns={0:'item_id'})

result

,item_id,0_Action,0_Adventure,0_Animation,0_Children's,0_Comedy,0_Crime,0_Documentary,0_Drama,0_Fantasy,...,0_Horror,0_Musical,0_Mystery,0_Romance,0_Sci-Fi,0_Thriller,0_War,0_Western,literal,title
0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AnimationChildren'sComedy,Toy Story (1995)
1,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AdventureChildren'sFantasy,Jumanji (1995)
2,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,ComedyRomance,Grumpier Old Men (1995)
3,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ComedyDrama,Waiting to Exhale (1995)
4,5.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Comedy,Father of the Bride Part II (1995)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Comedy,Meet the Parents (2000)
3879,3949.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Drama,Requiem for a Dream (2000)
3880,3950.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Drama,Tigerland (2000)
3881,3951.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Drama,Two Family House (2000)
3882,3952.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,DramaThriller,"Contender, The (2000)"

Exportamos a csv, la opcion index=false elimina de la exportacion los nombres de las filas

In [17]:
result.to_csv( PATH+"movies_one_hot_genre.csv",index=False)